default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  pool: 5
  username: yournamehere

development:
  <<: *default
  database: core_revival_dev

test:
  <<: *default
  database: core_revival_test
