default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  pool: 5
  username: adamlingo

# this is for humans
development:
  <<: *default
  database: clean_slate_dev


# this is for robots - do not touch
# tell the robot to use it with  'rake test'
test:
  <<: *default
  database: clean_slate_test
